config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews,  dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { in: 0..5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @ratings = Review.all.map { |review| review.rating }
    @average_ratings = @ratings.sum/@ratings.count
    @restaurant_ratings = Review.group(:restaurant_id).sum(:rating)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant: @restaurant)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container shadow p-3 m-4 bg-white rounded ">
  <div class="align-items-center">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h3>All Restaurants</h3>

  <% @restaurants.each do |restaurant|%>

    <div class="d-flex justify-content-start shadow p-4 m-4 bg-light rounded align-items-center">
      <div>
        <img src=<%= restaurant.image_url %> alt="" class="img-fluid" style="width: 250px;">
      </div>

      <div class="ms-4">
        <h5> <%= link_to restaurant.name, restaurant %> </h5> <br>
        <p> <strong>Address: </strong><%= restaurant.address %> </p>
        <p> <strong>Phone number: </strong><%= restaurant.phone_number %> </p>
        <p> <strong>Category: </strong><%= restaurant.category %> </p>
        <p> <strong>Average rating: </strong><%= "⭐" * @average_ratings %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-center">
    <div>
      <img src=<%= @restaurant.image_url %> alt="" class="img-fluid" style="width: 350px;">
    </div>
    <div class="m-4">
      <div>
        <h3><%= @restaurant.name %> </h3>
        <%= link_to "✏️ Edit restaurant", edit_restaurant_path(@restaurant) %>
      </div>
      <div class="mt-4">
        <p> <strong>Address: </strong><%= @restaurant.address %> </p>
        <p> <strong>Phone number: </strong><%= @restaurant.phone_number %> </p>
        <p> <strong>Category: </strong><%= @restaurant.category %> </p>
      </div>
    </div>
  </div>
  <% @reviews.each do |review|%>
    <div class="shadow p-4 m-4 bg-light rounded align-items-center">
      <p> <%= "⭐" * review.rating %> </p>
      <p> <strong>Review: </strong><%= review.content %> </p>
    </div>
  <% end %>


  <%= link_to "➕ Add review", new_restaurant_review_path(@restaurant) %> <br>
  <%= link_to "🔍 View all restaurants", restaurants_path %>
</div>

app/views/reviews/new.html.erb
<div class="container mt-5">
  <h3> <%= @restaurant.name %> New Review </h3>

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit %>
  <% end %>
</div>